#!/bin/bash 

en_monitoring ()
{
    while ! pgrep -aP $$ | grep -q teeworlds-server
    do
	sleep 0.1
    done
    while pgrep -aP $$ | grep -q teeworlds-server
    do
	
        tail -n0 -f "$1" | \
            grep -m1 -A1 "^\[[[:xdigit:]]\{8\}\]\[server\]: player has entered the game" | \
	    sed -e \
		's/^\[[[:xdigit:]]\{8\}\]\[server\]: player has entered the game. ClientID=.* addr=\(.*\).*/Enter:\naddr=\1/' -e \
		"s/^\[[[:xdigit:]]\{8\}\]\[chat\]: \*\*\* '\(.*\)' entered and joined.*/name=\1\ndate=/" | \
	    awk '{ if ($1 == "date=") print "date="strftime("%d-%m-%Y %H:%M:%S %Z")"\n"; else print $0 }' >> "$BD"
    done
}

lv_monitoring ()
{
   while ! pgrep -aP $$ | grep -q teeworlds-server
   do
	sleep 0.1
   done
   while pgrep -aP $$ | grep -q teeworlds-server
   do
       tail -n0 -f "$1" | \
	   grep -m1 -A1 "^\[[[:xdigit:]]\{8\}\]\[game\]: leave player" | \
	   sed -e \
	       "s/^\[[[:xdigit:]]\{8\}\]\[game\]: leave player='[0-9]*:\(.*\)'/Leave:\nname=\1\ndate=/" -e \
	       "/^\[[[:xdigit:]]\{8\}\]\[game\]: Teams are/d" | \
	   awk '{ if ($1 == "date=") print "date="strftime("%d-%m-%Y %H:%M:%S %Z")"\n"; else print $0 }' >> "$BD"
   done
}
botsmon ()
{
  
    while ! pgrep -aP $$ | grep -q teeworlds-server
    do
	sleep 0.1
    done
    
   while pgrep -aP $$ | grep -q teeworlds-server
   do
       tail -n0 -f "$1" | grep -m1 "^\[[[:xdigit:]]\{8\}\]\[chat\]: \*\*\* Bots removed$"
	${HOME}/.teeworlds/servertools/removebots
   done
}
clearall ()
{
    echo -e "Server closed ${SESSID} ${port:-8303} $(date --rfc-3339 s)\n" >> "$BD"
    pgrep -P $$ | xargs -I {} pkill -P {} &>/dev/null
}
while getopts ":p:" var
do
    case $var in
	p) port="sv_port $OPTARG" ;;
	*) echo "Incorrect option" && exit 1 ;;
    esac
done
trap "clearall" 0
trap "exit 0" 1 2 3 13 15

SESSID=$(mcookie)
BD="${HOME}/.teeworlds/players"
logfile="${HOME}/.teeworlds/serverlogs/teeservlog$(date "+%D-%T" | sed 's=[/:]=-=g')"

touch "$logfile"
en_monitoring "$logfile" &
lv_monitoring "$logfile" &
botsmon "$logfile" &

echo -e "Server started ${SESSID} ${port:-8303} $(date --rfc-3339 s)\n" >> "$BD"
echo "Server started"

teeworlds-server "$port" > "$logfile"

echo "Server closed"
